### PR TITLE
configurable storage class

### LINKED ISSUE #202: Storage class as a setting
It would make sense to me that the file storage class could be selected as a configuration, especially since many deployments these day are on ephemeral file systems.

We could set `storage`, something like this (untested):

```
from django.core.files.storage import get_storage_class
from django.conf import settings

storage_class = getattr(settings, 'SILKY_STORAGE_CLASS', 'silk.models.ProfilerResultStorage')
silky_storage = get_storage_class(storage_class)()

class Request(models.Model):
    # [...]
    prof_file = FileField(null=True, storage=silky_storage)
```

### PR DESCRIPTION
**Pull request by smcoll**
fixes #202

### CODE REVIEW

**Comment by smcoll** [comment]
Rebased.  Note that the docs are updated and i've moved the default storage class to a new location.

**Comment by avelis** [comment]
@smcoll Since this is introducing the concept of a customize-able storage. I am wondering if makes sense to add some config level tests asserting default behavior.

Thoughts?

**Comment by smcoll** [comment]
Yes, i agree.  i'll add a test asserting the default storage class is used when the setting is not specified.  Would that be sufficient?

**Comment by avelis** [comment]
@smcoll Yes that would be sufficient!

**Comment by smcoll** [comment]
@avelis added- does that work?

**Comment by avelis** [comment]
@smcoll Yes. Works for me. Thanks again for adding the test.

**Pull request merged**
