### PR TITLE
Opening sql queries in new tab is very useful

### PR DESCRIPTION
**Pull request by lokeshatbigbasket**
We may want to open the links in sql details page in new tab. Please review and approve this PR.

### CODE REVIEW

**Comment by lokeshatbigbasket** [comment]
Only one job has failed in build...

**Comment by lokeshatbigbasket** [comment]
Can anyone merge this PR

**Comment by avelis** [comment]
@lokeshatbigbasket I hear you. I wonder if it's of any use to make this as an optional setting. However, I am not sure adding that complexity is worth it.

**Comment by lokeshatbigbasket** [comment]
I felt that when we have list of SQL queries for a request, we might need them to open each query in new tab not in the same tab and going back every time, when handling a larger projects like us, it would add great benefit...

**Comment by avelis** [comment]
@lokeshatbigbasket I agree on the benefit 👍. I appreciate you making the enhancement! 😀

**Comment by lokeshatbigbasket** [comment]
@avelis thank you very much...

**Comment by none-da** [comment]
:+1: @lokeshatbigbasket

**Pull request merged**
