### PR TITLE
Fix Django 2 deprecations

### PR DESCRIPTION
**Pull request by albertyw**
Fix some deprecations to make silk compatible with django 2.0

### CODE REVIEW

**Comment by avelis** [comment]
@albertyw I appreciate the work future proofing silk for Django 2. TravisCI is highlighting an error.
```
    middleware_installed = 'silk.middleware.SilkyMiddleware' in getattr(settings, 'MIDDLEWARE', [])
TypeError: argument of type 'NoneType' is not iterable
```
Is it possible for you to look into that so I can merge this in?

**Comment by avelis** [comment]
@albertyw Thanks for addressing Django 2 deprecations!

**Comment by albertyw** [comment]
Next time, can we not squash commits?  With pypi behind with releases, some people (at least me) are pinning to github hashes and if you squash commits, it means those exact commits don't get merged into master.

**Comment by avelis** [comment]
@albertyw Yes I can do that.

**Pull request merged**
